//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mulligan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> EntryFee { get; set; }
        public Nullable<int> EntryLimit { get; set; }
        public string Passcode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public int TournamentId { get; set; }
    
        public virtual Tournament Tournament { get; set; }
    }
}
