//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mulligan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentPlayer
    {
        public int Id { get; set; }
        public int Score { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Tier { get; set; }
        public int PlayerId { get; set; }
        public int TournamentId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
